### ISSUE TITLE
Codox improperly handles return type tags

### ISSUE THREAD

**Issue by jhalterman** [weavejester/codox#103]
Using 0.9.0, return type tags such as this:

```clojure
(defn close-async!
  "Closes the `atomix` , server or replica."
  ^CompletableFuture
  [^Atomix atomix]
  (.close atomix))
```

Produces codox such as:

![screen shot 2015-11-05 at 12 34 53 pm](https://cloud.githubusercontent.com/assets/228804/10980964/a395d9b4-83b9-11e5-92da-adf34a9c1e77.png)

...where the presence of the return type tag causes the function name `close-async!` to be show up as the first parameter name.

**Comment by weavejester** [comment]
The second line is meant to contain the function name. That behavior isn't due to the return type tag, it's just how Codox always renders its function documentation.
