### ISSUE TITLE
Generated source uris with version key

### ISSUE THREAD

**Issue by cldwalker** [weavejester/codox#107]
Hi. Thanks for this helpful library! I'm looking to generate :source-uri with the current version of a project e.g.

```cljs
:codox {:source-uri "https://github.com/foo/bar/blob/{version}/{filepath}#L{line}"}
```

I realize that I could bump the version on every release which seems to be what you do for [compojure](https://github.com/weavejester/compojure/blob/7bd602d5ff28b6421993d32bee2c26da0460e0a2/project.clj#L13). I'm looking to remove this manual step since I'd like to have a post-release script that generates api documentation. Would you take a PR that adds this support to [html/var-source-uri](https://github.com/weavejester/codox/blob/be11a4245140dd61893554ddda8503a18d71d952/codox/src/codox/writer/html.clj#L92)? Seems it could pull this information from `[:project :version]`. Cheers

**Comment by weavejester** [comment]
Yes, that should be fine.
