### ISSUE TITLE
Update default theme or ship with multiple writers?

### ISSUE THREAD

**Issue by cldwalker** [weavejester/codox#109]
Hi again. [For LightTable](https://github.com/LightTable/LightTable/issues/2062), we would like to improve the styling of the api docs. Would you be interested in updating the default style to look like?

<img width="1440" alt="screen shot 2015-12-07 at 1 34 59 am" src="https://cloud.githubusercontent.com/assets/11994/11620653/ed79fcc2-9c82-11e5-80cf-5ff335339163.png">

The style comes from a [codox fork](https://github.com/funcool/codeina) with the Eclipse License. I think the style looks more modern and is easier to navigate on a phone. If you're not interested in changing the default styling, would you be interested in having it ship as a second theme e.g. `{:codox {:theme :new-theme}}`?  As for the changes involved, the writers between the two themes share most of the same code. Almost all the differences are in default.css and in index-page, namespace-page and namespaces-menu.

**Comment by weavejester** [comment]
I much prefer the current theme, so I don't want to update the default.

You can override the writer with the `:writer` configuration key, so you can do something like:

```clojure
:dependencies [[codina-theme "0.1.0"]]
:plugins [[lein-codox "0.9.0"]]
:codox {:writer codina-theme.writer/write-docs}
```

This allows Codox to have whatever theme you wish, or even to write to different formats.

**Comment by cldwalker** [comment]
@weavejester Seems reasonable. Once I publish the theme to clojars would you be interested in starting a README section or wiki page for out of the box themes that can be used with :writer? I think it would be helpful for codox to encourage sharing out-of-the-box themes. Any suggestion on a clojar name for this e.g. `codox-theme-`?

**Comment by weavejester** [comment]
`codox-theme-` seems fine, and I think it's a good idea to add themes to the README.

**Comment by cldwalker** [comment]
Sounds good. Will PR when we have a theme clojar up
