### ISSUE TITLE
Alternative styling options

### ISSUE THREAD

**Issue by j-allard** [weavejester/codox#111]
Hi, 
Is there currently a way to control the default styling used for the generated docs ?
As far as I can see right now `default.css` seems to be hard-coded.
I think having a lein option to declare a custom css file would be nice.
Is there any plans for this? 

Thanks :-)

**Comment by weavejester** [comment]
You can change the default writer to a custom function, allowing for complete control over the output.

However, you can't currently specify additional CSS rules for the default writer. I'd accept a patch for this.
