### ISSUE TITLE
Bitbucket Line number anchors don't work.

### ISSUE THREAD

**Issue by preoctopus** [weavejester/codox#115]
This was mentioned in #10, but it looks like bitbucket has changed the way they do anchors.

Perhaps I'm just missing something, but the anchor links for each line on bitbucket include the filename you are currently viewing. 

For example:
https://bitbucket.org/[username]/[project-name]/src/master/src/stuff/core.clj#core.clj-2

and for other.clj the anchor would be #other.clj-99

It's possible to assign a static one, but I can't seem to find a way to make it link properly.

**Comment by weavejester** [comment]
So to fix this, presumably a `{basename}` parameter for the link template would work? i.e.

    https://bitbucket/foo/bar/src/{version}/{filepath}#{basename}-{line}

**Comment by preoctopus** [comment]
I think that's all it needs. :+1:

**Comment by preoctopus** [comment]
Wow! You're the best. 

Thank you very much!
