### ISSUE TITLE
"Could not find artifact boot-codox:boot-codox:jar:0.9.4 in clojars"

### ISSUE THREAD

**Issue by konukhov** [weavejester/codox#121]
Hi! 

It turns out `boot-codox` isn't on Clojars yet. 

```org.sonatype.aether.resolution.ArtifactResolutionException: Could not find artifact boot-codox:boot-codox:jar:0.9.4 in clojars (https://clojars.org/repo/)```

Could you please push it there?

Thanks!

**Comment by weavejester** [comment]
I'll release 0.9.5 tomorrow. It slipped my mind to release a new version.

**Comment by konukhov** [comment]
Thank you.

**Comment by weavejester** [comment]
Codox 0.9.5 (including boot-codox) is now released.

**Comment by konukhov** [comment]
Thanks James!
