### ISSUE TITLE
Add support for specs

### ISSUE THREAD

**Issue by kumarshantanu** [weavejester/codox#128]
Please consider adding support for specs introduced in Clojure 1.9 - I am not sure whether this should be configurable or not, but this may impact #79 

References:
http://clojure.github.io/java.jdbc/#clojure.java.jdbc/create-table-ddl
http://clojure.github.io/java.jdbc/#clojure.java.jdbc.spec

**Comment by weavejester** [comment]
Adding support for clojure.spec is a good idea. I'd welcome any PR that implements this.
