### ISSUE TITLE
Workflow for auto-generating documentation

### ISSUE THREAD

**Issue by xiongtx** [weavejester/codox#142]
Can you describe a good workflow for auto-generating documentation for a project's GitHub page?

Ideally, to automate the process, documentation should be generated before every commit. Is this a job for [Git commit hooks](https://www.digitalocean.com/community/tutorials/how-to-use-git-hooks-to-automate-development-and-deployment-tasks), or is there a better solution?

Projects like [Hiccup](http://weavejester.github.io/hiccup/) seem to use the `gh-pages` branch technique. For these projects, is documentation manually, then copied over to that branch? What automation, if any, is involved?

**Comment by weavejester** [comment]
Take a look at [Deploying to GitHub Pages](https://github.com/weavejester/codox/wiki/Deploying-to-GitHub-Pages) for information about how to easily deploy to the `gh-pages` branch.

In general I just generate the documentation then commit and push the changes. I guess I could automate it further, but releases are rare enough that I haven't felt the need.

**Comment by xiongtx** [comment]
Should have checked the Wiki first!

It seems to me that if the GitHub page is purely for documentation, [pointing the page at `master/docs`](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch) seems easier. Although, it might make diffs more cluttered?
