### ISSUE TITLE
Google analytics

### ISSUE THREAD

**Issue by rm-hull** [weavejester/codox#150]
Hi James, would you consider accepting a patch that would add Google Analytics to the codox pages?

I would envisage that the plugin would check for the presence the following setting in the project.clj:

```clojure
:codox {:google-analytics { :tracking-code :UA-11111111-1 } }
```

Then this would inject the following inline javascript onto every generated page (taken from the GA admin page):

```html
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-11111111-1', 'auto');
  ga('send', 'pageview');

</script>
```

Let me know what you think and I'll put a PR together.

**Comment by weavejester** [comment]
I think it would be better to package this as a theme. You'd get the same functionality, but it wouldn't be hard coded.

```clojure
:dependencies [[google-analytics-codox-theme "0.1.0"]]
:codox {:themes [:default [:google-analytics {:tracking-code "UA-11111111-1"}]]}
```

**Comment by rm-hull** [comment]
That seems a pretty neat way to do it - i'll do that instead - thanks!

**Comment by rm-hull** [comment]
FYI - published this: https://clojars.org/google-analytics-codox-theme

**Comment by weavejester** [comment]
I was thinking of starting a wiki page for Codox themes. Mind if I add your link to it?

Also, I believe the `:dev-dependencies` key has been retired in favour of the `:dev` profile instead.

**Comment by rm-hull** [comment]
> Mind if I add your link to it?

Sure - go for it

> :dev-dependencies key has been retired 

Updated README
