### ISSUE TITLE
[0.10.2] Excluding var ns/->MyRecord by default

### ISSUE THREAD

**Issue by hlship** [weavejester/codox#154]
Using 0.10.2, all the public `defrecord` related vars are excluded.  Reverting to 0.9.7 generates the documentation for these. I suspect the new feature to exclude vars from a namespace may be overly aggressive.

**Comment by weavejester** [comment]
If I've understood you correctly, that's the right default behavior, as most of the time people don't want automatically generated vars in their documentation.

You can disable this behavior by setting the `:exclude-vars` key to `nil`. It's mentioned in the README.

```clojure
:codox {:exclude-vars nil}
```

**Comment by hlship** [comment]
Sorry, I must have missed that in the README.
