### ISSUE TITLE
Migrate from pegdown to flexmark-java

### ISSUE THREAD

**Issue by Josh-Tilles** [weavejester/codox#158]
This issue is closer to a heads-up than a bug or feature request; I thought you’d want to know that [pegdown has been deprecated][1] in favor of [flexmark-java][2]. I do _not_ have any specific problems that flexmark-java would solve, but I’ll report back if any come up.

[1]: https://github.com/sirthias/pegdown/tree/19ca3d3d2bea5df19eb885260ab24f1200a16452#-deprecation-note-
[2]: https://github.com/vsch/flexmark-java

**Comment by weavejester** [comment]
Thanks for the heads-up!

**Comment by genmeblog** [comment]
I believe it's necessary now, Pegdown (Parboiled dependency) stopped working on JDK16+ See #197

**Comment by weavejester** [comment]
I'll prioritise reviewing and merging a PR that fixes this.
