### ISSUE TITLE
codox depends on leiningen

### ISSUE THREAD

**Issue by stuarthalloway** [weavejester/codox#163]
I am considering codox for an environment where leiningen is not approved. Is there a reason that codox requires leiningen?

**Comment by weavejester** [comment]
Codox doesn't require Leiningen. What makes you think that?

**Comment by stuarthalloway** [comment]
This output from `mvn dependency:tree`

```
[INFO] \- codox:codox:jar:0.6.4:compile
[INFO]    \- codox:codox.leiningen:jar:0.6.4:compile
[INFO]       \- leinjacker:leinjacker:jar:0.4.1:compile
```
Hmm, reading a second time, maybe that isn't leiningen proper, just codox.leiningen and leinjacker. 

I work in some environments where each library must be approved, and since I am not using leiningen I would prefer to avoid having to review unnecessary deps.

**Comment by weavejester** [comment]
You're using Codox 0.6.4. That's *very* old, from 2012. Back then, Codox might have been more integrated with Leiningen, but that's so long ago I can't remember.

**Comment by stuarthalloway** [comment]
Thanks!  Now trying to figure out where that came from.
