### ISSUE TITLE
filter-namespaces option does not seem to work with boot / clojurescript

### ISSUE THREAD

**Issue by Yahtze** [weavejester/codox#174]
I can generate the docs just fine if I do not use the filter-namespaces option in my boot task, however when I do use it I get a `ClassNotFoundException: xyz-namespace.yaddayadda.asdf` for the namespace I tried to filter out.

``` clojure
(deftask docs []
  (set-env! :source-paths #{"src/cljs"})
  (comp
    (codox
      :name "asdf"
      :description "asdf"
      :language :clojurescript
      :version "1.0.0"
      :filter-namespaces #{xyz-namespace.yaddayadda.asdf}
      :metadata {:doc/format :markdown})
    (target)))
```
any help would be greatly appreciated, thank you.

**Comment by weavejester** [comment]
I'm not an expert on Boot, but shouldn't the namespace be quoted?

**Comment by Yahtze** [comment]
@weavejester indeed it does. Thank you very much
