### ISSUE TITLE
can't generate Clojurescript docs on re-frame template 

### ISSUE THREAD

**Issue by evilsneer** [weavejester/codox#196]
hi! I have the error with doc generation on app https://github.com/day8/re-frame-template.

`{:clojure.main/message✗ 
 "Syntax error (IllegalStateException) compiling at (/private/var/folders/tb/j655qh1n2nv166t5c0qm8p640000gp/T/form-init5325346300118268983.clj:1:125).\nnull\n",
 :clojure.main/triage
 {:clojure.error/phase :compile-syntax-check,
  :clojure.error/line 1,
  :clojure.error/column 125,
  :clojure.error/source "form-init5325346300118268983.clj",
  :clojure.error/path
  "/private/var/folders/tb/j655qh1n2nv166t5c0qm8p640000gp/T/form-init5325346300118268983.clj",
  :clojure.error/class java.lang.IllegalStateException},
 :clojure.main/trace
 {:via
  [{:type clojure.lang.Compiler$CompilerException,
    :message
    "Syntax error compiling at (/private/var/folders/tb/j655qh1n2nv166t5c0qm8p640000gp/T/form-init5325346300118268983.clj:1:125).",
    :data
    {:clojure.error/phase :compile-syntax-check,
     :clojure.error/line 1,
     :clojure.error/column 125,
     :clojure.error/source
     "/private/var/folders/tb/j655qh1n2nv166t5c0qm8p640000gp/T/form-init5325346300118268983.clj"},
    :at [clojure.lang.Compiler load "Compiler.java" 7648]}
   {:type java.lang.Exception,
    :message "Could not load codox writer codox.writer.html",
    :at [codox.main$writer$fn__747 invoke "main.clj" 16]}
   {:type clojure.lang.Compiler$CompilerException,
    :message "Syntax error macroexpanding def at (html.clj:66:1).",
    :data
    {:clojure.error/phase :execution,
     :clojure.error/line 66,
     :clojure.error/column 1,
     :clojure.error/source "html.clj",
     :clojure.error/symbol def},
    :at [clojure.lang.Compiler$DefExpr eval "Compiler.java" 470]}
   {:type java.lang.reflect.InvocationTargetException,
    :at
    [sun.reflect.NativeConstructorAccessorImpl
     newInstance0
     "NativeConstructorAccessorImpl.java"
     -2]}
   {:type java.lang.RuntimeException,
    :message "Error creating extended parser class: null",
    :at [org.parboiled.Parboiled createParser "Parboiled.java" 58]}
   {:type java.lang.IllegalStateException,
    :at
    [org.objectweb.asm.tree.analysis.BasicInterpreter
     <init>
     "BasicInterpreter.java"
     66]}],
  :trace
  [[org.objectweb.asm.tree.analysis.BasicInterpreter
    <init>
    "BasicInterpreter.java"
    66]
   [org.parboiled.transform.RuleMethodInterpreter
    <init>
    "RuleMethodInterpreter.java"
    42]
   [org.parboiled.transform.InstructionGraphCreator
    process
    "InstructionGraphCreator.java"
    41]
   [org.parboiled.transform.ParserTransformer
    runMethodTransformers
    "ParserTransformer.java"
    62]
   [org.parboiled.transform.ParserTransformer
    extendParserClass
    "ParserTransformer.java"
    45]
   [org.parboiled.transform.ParserTransformer
    transformParser
    "ParserTransformer.java"
    38]
   [org.parboiled.Parboiled createParser "Parboiled.java" 54]
   [org.pegdown.PegDownProcessor <init> "PegDownProcessor.java" 94]
   [org.pegdown.PegDownProcessor <init> "PegDownProcessor.java" 73]
   [sun.reflect.NativeConstructorAccessorImpl
    newInstance0
    "NativeConstructorAccessorImpl.java"
    -2]
   [sun.reflect.NativeConstructorAccessorImpl
    newInstance
    "NativeConstructorAccessorImpl.java"
    62]
   [sun.reflect.DelegatingConstructorAccessorImpl
    newInstance
    "DelegatingConstructorAccessorImpl.java"
    45]
   [java.lang.reflect.Constructor newInstance "Constructor.java" 423]
   [clojure.lang.Compiler$NewExpr eval "Compiler.java" 2615]
   [clojure.lang.Compiler$DefExpr eval "Compiler.java" 457]
   [clojure.lang.Compiler eval "Compiler.java" 7182]
   [clojure.lang.Compiler load "Compiler.java" 7636]
   [clojure.lang.RT loadResourceScript "RT.java" 381]
   [clojure.lang.RT loadResourceScript "RT.java" 372]
   [clojure.lang.RT load "RT.java" 459]
   [clojure.lang.RT load "RT.java" 424]
   [clojure.core$load$fn__6839 invoke "core.clj" 6126]
   [clojure.core$load invokeStatic "core.clj" 6125]
   [clojure.core$load doInvoke "core.clj" 6109]
   [clojure.lang.RestFn invoke "RestFn.java" 408]
   [clojure.core$load_one invokeStatic "core.clj" 5908]
   [clojure.core$load_one invoke "core.clj" 5903]
   [clojure.core$load_lib$fn__6780 invoke "core.clj" 5948]
   [clojure.core$load_lib invokeStatic "core.clj" 5947]
   [clojure.core$load_lib doInvoke "core.clj" 5928]
   [clojure.lang.RestFn applyTo "RestFn.java" 142]
   [clojure.core$apply invokeStatic "core.clj" 667]
   [clojure.core$load_libs invokeStatic "core.clj" 5985]
   [clojure.core$load_libs doInvoke "core.clj" 5969]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.core$apply invokeStatic "core.clj" 667]
   [clojure.core$require invokeStatic "core.clj" 6007]
   [clojure.core$require doInvoke "core.clj" 6007]
   [clojure.lang.RestFn invoke "RestFn.java" 408]
   [codox.main$writer$fn__747 invoke "main.clj" 13]
   [codox.main$writer invokeStatic "main.clj" 12]
   [codox.main$writer invoke "main.clj" 9]
   [codox.main$generate_docs invokeStatic "main.clj" 122]
   [codox.main$generate_docs invoke "main.clj" 116]
   [user$eval841 invokeStatic "form-init5325346300118268983.clj" 1]
   [user$eval841 invoke "form-init5325346300118268983.clj" 1]
   [clojure.lang.Compiler eval "Compiler.java" 7177]
   [clojure.lang.Compiler eval "Compiler.java" 7166]
   [clojure.lang.Compiler eval "Compiler.java" 7167]
   [clojure.lang.Compiler load "Compiler.java" 7636]
   [clojure.lang.Compiler loadFile "Compiler.java" 7574]
   [clojure.main$load_script invokeStatic "main.clj" 475]
   [clojure.main$init_opt invokeStatic "main.clj" 477]
   [clojure.main$init_opt invoke "main.clj" 477]
   [clojure.main$initialize invokeStatic "main.clj" 508]
   [clojure.main$null_opt invokeStatic "main.clj" 542]
   [clojure.main$null_opt invoke "main.clj" 539]
   [clojure.main$main invokeStatic "main.clj" 664]
   [clojure.main$main doInvoke "main.clj" 616]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.main main "main.java" 40]],
  :phase :compile-syntax-check}}
`

have been set
`  :codox {:language :clojurescript}`

have deps:

`:dependencies [[org.clojure/clojure "1.10.1"]
                 [org.clojure/clojurescript "1.10.773"
                  :exclusions [com.google.javascript/closure-compiler-unshaded
                               org.clojure/google-closure-library
                               org.clojure/google-closure-library-third-party]]
                 [thheller/shadow-cljs "2.11.14"]
                 [reagent "1.0.0"]
                 [re-frame "1.1.2"]
                 [re-com "2.10.1"]
                 [clj-commons/secretary "1.2.4"]
                 [garden "1.3.10"]
                 [ns-tracker "0.4.0"]
                 [compojure "1.6.2"]
                 [yogthos/config "1.1.7"]
                 [ring "1.8.2"]
                 [re-pressed "0.3.1"]
                 [breaking-point "0.1.2"]
                 [martian "0.1.14"]
                 [martian-cljs-http "0.1.14"]
                 [martian-re-frame "0.1.14"]
                 [akiroz.re-frame/storage "0.1.4"]
                 [day8.re-frame/http-fx "0.2.2"]
                 [lambdaisland/uri "1.4.54"]]`

**Comment by weavejester** [comment]
Check your dependency tree for conflicts. That's usually the root cause of issues like this.

**Comment by weavejester** [comment]
Try including `[codox "0.10.7"]`manually in your dependencies, then running `lein deps :tree`.

**Comment by evilsneer** [comment]
Did it. 
Now codox shows in list of all dependencies, but not in "Possibly confusing dependencies" block (I guess it means there is no conflicts?). So I still don't know what specific dependency is need to be fixed :(

**Comment by weavejester** [comment]
I checked out the dependencies. There's a conflict between Codox, which requires:

```
 [codox "0.10.7"]
   [org.pegdown/pegdown "1.6.0"]
     [org.parboiled/parboiled-java "1.1.7"]
       [org.ow2.asm/asm "5.0.3"]
```

And shadow-cljs:

```
[thheller/shadow-cljs "2.11.14"]
   [org.graalvm.js/js "20.1.0"]
     [org.ow2.asm/asm "7.1"]
```

You'll have to experiment with exclusions or dependency overrides. You could also look into [cljdoc](https://github.com/cljdoc/cljdoc/), a fork of Codox, and I'd welcome any PR that converted Pegdown to something more modern, like [flexmark-java](https://github.com/vsch/flexmark-java).

**Comment by evilsneer** [comment]
I made profile on project file
`   :codox   {:managed-dependencies [[org.ow2.asm/asm-analysis "5.0.3"]]}`
and with it all works perfectly 👍
