### ISSUE TITLE
In deps.edn projects, lookup qualified keywords in exec-args as aliases in basis

### ISSUE THREAD

**Issue by cap10morgan** [weavejester/codox#204]
We store our version string in deps.edn as an alias named `:mvn/version`, and I would like to reference it in my codox exec-args like this: `{:version :mvn/version}` but I just get the string "version" in my generated docs instead of what `:mvn/version` points to.

Here's an example of how another library handles this: https://github.com/seancorfield/depstar/blob/d15af202cc796eecf9ef1b7df1c2108d4ee0a202/src/hf/depstar/task.clj#L14

**Comment by weavejester** [comment]
Can you explain a little further? How is the content of `:mvn/version` being passed into the running process?

**Comment by cap10morgan** [comment]
Like that code I link to demonstrates, when a value is a keyword, you just check if that keyword is an alias in the project basis (i.e. the deps.edn file). If it is, use the value of that alias in place of the original keyword in the exec-args.

Getting the aliases: https://github.com/seancorfield/depstar/blob/d15af202cc796eecf9ef1b7df1c2108d4ee0a202/src/hf/depstar/task.clj#L23-L26

Putting the value of the alias into the opts map when it a) exists and b) isn't an exec-arg that's supposed to be a keyword: https://github.com/seancorfield/depstar/blob/d15af202cc796eecf9ef1b7df1c2108d4ee0a202/src/hf/depstar/task.clj#L28-L34

**Comment by weavejester** [comment]
I don't think this is a good idea, because it's counter to the ethos of simplicity that tools.deps follows. If we change `generate-docs` to have behaviour dependent on deps.edn, that's a source of complexity. It creates a connection between deps.edn and `generate-docs` that didn't exist previously.

**Comment by cap10morgan** [comment]
Yeah, it would be nice if this substitution were done at the tools.deps level so it would just be there by the time you received the exec-args. It’s really unfortunate to have to repeat values like this (and remember to update them in more than one place).

But I hear you, it’s not really within codox’s domain to do this like it is for something like depstar.

I’ll look into other options.
