### ISSUE TITLE
`:project` key in deps.edn is ignored.

### ISSUE THREAD

**Issue by IGJoshua** [weavejester/codox#206]
I have a small project that I'm trying to get running with codox, and I noticed that the `:project` key is ignored by codox.main, and lein-codox actually does some special stuff to get it involved.

Is there a way for me to get the `:project` key working on the current version of codox?

**Comment by weavejester** [comment]
The `:project` key is used to override values taken from the Leiningen project map. If you're using `generate-docs` directly, then use the keys (`:name`, `:version`, `:description`, etc.) directly in the options map.

**Comment by IGJoshua** [comment]
Thanks, that's helpful.
