### ISSUE TITLE
Accept a basis for tools.build compatibility

### ISSUE THREAD

**Issue by cap10morgan** [weavejester/codox#214]
I tried using codox from a tools.build build.clj program, but I couldn't get it to work because codox expects to have access to the full runtime classpath to do what it does. Normally in tools.build (or any other tools.deps "tool") all of this is encapsulated in a tools.deps.alpha basis value (and the top-level `:paths`, `:deps`, etc. are not available outside that as [documented here](https://clojure.org/reference/deps_and_cli#_aliased_tool_execution)).

Could codox be modified to optionally accept a basis and generate docs from that?

**Comment by weavejester** [comment]
I'm not quite sure what you mean by this. The "basis" that tools.build uses is internal to tools.build. It makes no sense for a separate and unrelated library like Codox to support the internal structures of another tool.

I don't know enough about tools.build to say what would be the most idiomatic way of achieving this. However, one potential solution is to add an alias for Codox in deps.edn, then to call that as a separate process from tools.build.

**Comment by cap10morgan** [comment]
> I'm not quite sure what you mean by this. The "basis" that tools.build uses is internal to tools.build. It makes no sense for a separate and unrelated library like Codox to support the internal structures of another tool.

Well, for better or worse, plenty of other tools do support it. I don't know if that's the idiomatic way to work with tools.build or not, though.

> 
> I don't know enough about tools.build to say what would be the most idiomatic way of achieving this. However, one potential solution is to add an alias for Codox in deps.edn, then to call that as a separate process from tools.build.

Yeah, that's what I'm doing now. Just seemed like there should be a way to call it from the build program without shelling out.

**Comment by cap10morgan** [comment]
Based on a conversation with Alex Miller in Slack, it sounds like you're right that accepting a basis isn't the best approach. I'm trying to figure out what is. But for now it very well may be invoking a separate process. I'll close this for now.

**Comment by cap10morgan** [comment]
Sounds like once this is implemented it will be the idiomatic way to use libraries like codox from tools.build: https://clojure.atlassian.net/browse/TBUILD-6

...and you shouldn't need any modifications to what you already support. So yay! :)
