### ISSUE TITLE
Generate docs only for subtree?

### ISSUE THREAD

**Issue by sdegutis** [weavejester/codox#31]
Given these example namespaces:

```
mysite.features.blog
mysite.features.store
mysite.features.contact
mysite.view.web
mysite.view.cli
mysite.db.datomic
```

is there a way to generate docs for every namespace under `mysite.features` without having to name each of them explicitly?

**Comment by mtnygard** [comment]
This is a feature that I would also appreciate. It would be nice to have :include and :exclude support namespace prefixes.
