### ISSUE TITLE
exclude anonymous types

### ISSUE THREAD

**Issue by swannodette** [weavejester/codox#72]
`reify` generates anonymous types would should not appear in documentation. ClojureScript master now annotates the metadata of the var for these types with `:anonymous` set to `true`. It would be great if Codox could use this to exclude.

**Comment by weavejester** [comment]
I'm using ClojureScript 2760, but I can't see the `:anonymous` metadata when I use the analyzer. Nor can I find any mention of such a keyword in the [analyzer source](https://github.com/clojure/clojurescript/blob/master/src/clj/cljs/analyzer.clj).

When I run the analyzer on one of the generated vars, I get:

```clojure
 {:protocol-inline nil,
  :name ->t5079,
  :variadic false,
  :file
  "/Users/jim/Code/Public/codox/codox.example/src/clojure/codox/example3.cljs",
  :method-params
  ([{:name meta5080,
     :binding-form? true,
     :op :var,
     :env {:column 3, :line 65, :context :expr},
     :column 3,
     :line 65,
     :info {:name meta5080, :shadow nil},
     :tag nil,
     :shadow nil}]),
  :protocol-impl nil,
  :column 3,
  :methods
  ({:tag codox.example3/t5079, :variadic false, :max-fixed-arity 1}),
  :line 65,
  :max-fixed-arity 1,
  :fn-var true,
  :arglists '([meta5080])}
```

I don't see anything in there that would tell me that this is a generated variable.

**Comment by swannodette** [comment]
@weavejester the anonymous bit is applied in the `reify` macro https://github.com/clojure/clojurescript/blob/master/src/clj/cljs/core.clj#L613. You'll want to look at the metadata of the name symbol.

**Comment by weavejester** [comment]
So this information isn't available via the analyzer? It's only available in a running ClojureScript environment?

**Comment by swannodette** [comment]
@weavejester it is available via the analyzer. But it probably won't be on the factory fns.

**Comment by weavejester** [comment]
So just using the analyzer, how would one determine whether a var is a factory function or not? I'm afraid I'm not hugely familiar with the analyzer's output.

**Comment by tedfoye** [comment]
@weavejester ```:anonymous``` was added to the ```reify``` macro in version r2411. You can see it in line 610 in https://github.com/clojure/clojurescript/blob/r2411/src/clj/cljs/core.clj

I have a fix for this and can submit a pull request, if you'd like.

My fix also includes ```(bind [an/*analyze-deps* false])```. Without this the ClojureScript analyzer fails on my Om projects.

**Comment by weavejester** [comment]
I'm happy to accept any patch for this issue. If you do fix more than one thing, however, please separate them out into individual PRs. It makes tracking them easier.
