### ISSUE TITLE
core.typed support

### ISSUE THREAD

**Issue by atroche** [weavejester/codox#80]
It'd be nice if Codox showed types in the API docs, similar to what [crossclj.info](http://crossclj.info/doc/re.typed/0.1.4/re.typed.html) does. Before I dive in, is this something you'd consider merging into the project, @weavejester?

**Comment by weavejester** [comment]
It's definitely something I've considered, for core.typed and other systems, so I'd welcome any patches to that effect.

**Comment by atroche** [comment]
I've had a crack at adding support for the reader: https://github.com/atroche/codox/compare/atroche/core.typed. Does this seem like the write approach? Checking each namespace would add around one second to the build time, but we could make it so that it only does `check-ns-info` if the namespace has core.typed in its dependencies.

Any thoughts so far?

**Comment by atroche** [comment]
Here's how it's looking after a [pretty simple change](https://github.com/atroche/codox/commit/c221eea06dbe16190968f747b4da99ba299ce46b):

![clj-sockets_core_documentation](https://cloud.githubusercontent.com/assets/29839/5894891/a81c0efc-a563-11e4-9eed-5fa3a1deb277.png)

I see the next steps as:

*    make it so that it only does this for namespaces that depend on core.typed
*    verify that it works on a variety of repos
*    add some tests
*    confirm the formatting / styling with you

Anything else I should do before submitting a PR?

Cheers!

**Comment by weavejester** [comment]
That looks good. You'll need to ensure it works fine when core.typed isn't a dependency of the base project, and I'll probably play around with the formatting a little before release.

**Comment by atroche** [comment]
Thanks James! Will get onto it soon

On 27 January 2015 at 12:06, James Reeves <notifications@github.com> wrote:

> That looks good. You'll need to ensure it works fine when core.typed isn't
> a dependency of the base project, and I'll probably play around with the
> formatting a little before release.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/weavejester/codox/issues/80#issuecomment-71571960>.
>



-- 
-- Alistair

**Comment by atroche** [comment]
What do you think of this approach? https://github.com/atroche/codox/commit/fad7a03e52a530954e59b45b87854f6ea0d9ac77

Seems a shame to have to thread that value through so many functions, but I can't think of an alternative…

**Comment by weavejester** [comment]
I'm afraid that wouldn't work, because `core.typed` could be included as a dependency of a dependency.

Instead, check to see whether a namespace exists and can be required, e.g. try `(require 'clojure.core.typed.check)` and if that fails, return false, otherwise true.

**Comment by atroche** [comment]
A much better idea!

How's [this](https://github.com/atroche/codox/commit/78bbb5efcb1729461182b95dc15ef71c0e04758d)?

P.S. @fbellomi [shared the code](https://gist.github.com/fbellomi/9832211d53bd0a1dd49b) for the core.typed pretty printer he uses on crossclj.info

**Comment by weavejester** [comment]
Can you make it into a PR? It's easier to manage that way.

**Comment by atroche** [comment]
Sure: https://github.com/weavejester/codox/pull/82

**Comment by oubiwann** [comment]
@atroche Hey man, I noticed that this branch/PR stalled out -- is this something you're you're planning in picking back up? I have a keen interest in seeing core.typed support land in Codox -- I'll take a look and see if this is something I'm comfortable contributing to, if you're amenable to that ... seems so close!

**Comment by atroche** [comment]
hey @oubiwann, I haven't used core.typed at all since a year ago, so I don't think I'll pick it up back up. But feel free to use whatever's there, and good luck!

**Comment by oubiwann** [comment]
@atroche Thanks, man -- digging in now :-)

**Comment by oubiwann** [comment]
New PR has been created for this effort: #117.

**Comment by yurrriq** [comment]
Using [0.9.4](https://github.com/weavejester/codox/releases/tag/0.9.4) with [a codebase](https://github.com/oubiwann/clojang) with annotated protocols, I'm noticing only the annotation(s) for the first method are showing up in the Codox output. `(ann ...)` forms for `defn` seem to be handled fine, but for `(ann-protocol ...)` forms, Codox seems to drop all but the first method annotation.

**Comment by weavejester** [comment]
Could you open a new issue with an example?

**Comment by yurrriq** [comment]
Will do.

**Comment by yurrriq** [comment]
In trying to produce a minimum failing case, Codox is behaving as expected, so it seems there's something else going on with [clojang](https://github.com/oubiwann/clojang)..

**Comment by yurrriq** [comment]
After some experimentation, it seems the multi-arity protocol methods are not the problem, nor the docstrings (neither protocol nor method level). My best guess at this point is that the trouble has something to do with [potemkin](https://github.com/ztellman/potemkin).

**Comment by oubiwann** [comment]
We can close this ticket now, yes?

**Comment by weavejester** [comment]
Yep
