### ISSUE TITLE
Testing the plugin while developing

### ISSUE THREAD

**Issue by atroche** [weavejester/codox#81]
Hey @weavejester,

What's your development process? So far I've adding my own project ([clj-sockets](https://github.com/atroche/clj-sockets)) as a dependency to `codox.core`, putting a symlink in checkouts, requiring it in the REPL and trying out the various fns in `codox.reader.clojure` on my projects namespace.

But now I want to trying running `lein doc` against my project and seeing the new output. I've added a `.lein-classpath` to my project root, and I've made sure that it's definitely running my local copy of `codox.leiningen/src/leiningen/doc.clj`. But I can't get `codox.leiningen` to use the local copy of `codox.main` (I've tried putting a symlink in `codox.leiningen/checkouts` to `codox.main/src`, to no avail).

Any tips?

**Comment by atroche** [comment]
P.S. as far as I can work out, none of the other popular Leiningen plugins use the same project layout as you:

https://github.com/emezeske/lein-cljsbuild
https://github.com/ato/lein-clojars
https://github.com/marick/lein-midje
https://github.com/relaynetwork/lein-release

If I made a PR converting the project structure to be more like those, how would you feel?

Cheers!

**Comment by weavejester** [comment]
Using `checkouts` inside the `codox.example` project should work. You can also use `lein install` to locally install packages, though that shouldn't be necessary.

I'm afraid I don't understand what you mean by project layout. All the repositories you link to contain a single project, whereas Codox is a repository with two projects; a library and a Leiningen plugin. Both library and plugin are structured in a very standard way.

**Comment by atroche** [comment]
Thanks! Adding a symlink to `codox.core` in my project worked.

As for the layout, I think I was just surprised by the whole “one repo for two projects” thing. Is the idea that people can add “codox” as a plugin or a dependency, and if they add it as a dependency they can `require` it? Or are they split up just to separate concerns? How come no one else does it?

**Comment by weavejester** [comment]
I don't see how else you'd logically structure a project like this. If you put all the code in a Leiningen plugin, then how would you accommodate people wanting to use Codox without Leiningen, or with a different build tool?

**Comment by atroche** [comment]
Yep! Makes sense now. Thanks for explaining =)
