### ISSUE TITLE
Adding non-code files

### ISSUE THREAD

**Issue by muhuk** [weavejester/codox#85]
[Immutant docs](http://immutant.org/documentation/current/apidoc/) have a section titled *"Guides"* before the API docs.

They seem to be rendering them manually and then creating a different index via [a plugin](https://github.com/immutant/immutant/tree/thedeuce/etc/build-helper/src/build_helper).

It would be awesome to have this feature directly in codox.

**Comment by weavejester** [comment]
Added in 0.9.0
