### ISSUE TITLE
Feature request: Document both Clojure and ClojureScript

### ISSUE THREAD

**Issue by jdeisenberg** [weavejester/codox#86]
I want to generate documentation for a project that is primarily written in ClojureScript but also has some Clojure (for macros). Is there some way to get dodox to parse both sections?

**Comment by weavejester** [comment]
Codox already documents Clojure macros when creating ClojureScript documentation.

**Comment by jdeisenberg** [comment]
I attempted to use Codox to create documentation for https://github.com/prismatic/dommy and set 
`:codox {:language :clojurescript}`. The generated documentation does not appear to include any of the macros in the `core.clj` file. Not sure what I am doing wrong, then. (Results are at https://github.com/jdeisenberg/dommy_docs)

**Comment by weavejester** [comment]
I tried generating docs for dommy with Codox, and then looked at your results. I'm afraid I don't understand what you think is missing. The core.html file contains all five macros from core.clj.

**Comment by jdeisenberg** [comment]
Ah; thank you. I see them now.
