### ISSUE TITLE
A case where indented code snippets don't work

### ISSUE THREAD

**Issue by marick** [weavejester/codox#89]
The following produces example code nicely indented under the description:

```clojure
(defn without-namespace
  "Return a symbol with the same name as `sym` but no 
   namespace.
   
        (symbol/without-namespace 'clojure.core/even?) => 'even?
"
```
![screen shot 2015-04-26 at 12 36 31 pm](https://cloud.githubusercontent.com/assets/71909/7338419/ed906584-ec10-11e4-890f-7529bad0f06c.png)

However, the following, which has a single line of description, does not:

```clojure
(defn without-namespace
  "Return a symbol with the same name as `sym` but no namespace.
   
        (symbol/without-namespace 'clojure.core/even?) => 'even?
"
```

![screen shot 2015-04-26 at 12 37 59 pm](https://cloud.githubusercontent.com/assets/71909/7338429/1fb516f4-ec11-11e4-96fc-1c9785225fdd.png)

[Original source](https://github.com/marick/suchwow/blob/1c26a8cffe99cc43835cfbd04bea11078d01ab8e/src/such/symbols.clj#L23)
```
  :dependencies [[org.clojure/clojure "1.6.0"]]
            [codox "0.8.11"]]
```

**Comment by weavejester** [comment]
Unfortunately, I don't think it's possible to determine indentation from a two-line docstring in a reliable way. Consider the following two examples:

```clojure
(defn foo
  "First line.

      Second line."
  []
  "foo")
```

```clojure
(let [x 1]
  (let [y 2]
    (defn bar []
      "First line.

      Second line."
      []
      "bar")))
```

Both vars have exactly the same docstring, but only `foo` should be considered as being indented.

It might be possible to determine the indentation from the blank line, but this means adding trailing whitespace, which can accidentally be cleaned up by automated tools.

**Comment by marick** [comment]
Adding the trailing whitespace to blank lines is what I do. It's fiddly, but it can be made to work - except in the case I quoted. 

I'm willing to pay the price of fiddling in order to have documentation with embedded examples. An automated tool that changed the contents of strings would find no home in my toolchain.

**Comment by marick** [comment]
But note: everything works now except for (as far as I can tell) the edge case, so all is well, really.

**Comment by weavejester** [comment]
Don't think there's a way to fix this given the constraints of markdown and docstrings, so I'm closing it.
