### ISSUE TITLE
clojurescript doc building broken with clojurescript >= 0.0.3030

### ISSUE THREAD

**Issue by retrogradeorbit** [weavejester/codox#90]
using 

```
:plugins [[lein-cljsbuild "1.0.5"]
            [codox "0.8.11"]
            [lein-environ "1.0.0"]
            [cider/cider-nrepl "0.8.2"]
            [com.cemerick/clojurescript.test "0.3.3"]
            ]
:codox {:language :clojurescript}
```

reads the cljs files but then dumps undeclared vars for every clojurescript core var:

```
$ lein doc 
WARNING: Use of undeclared Var cljs.core/LazySeq at line 66 src/cljs/argo/vec.cljs
WARNING: Use of undeclared Var cljs.core/LazySeq at line 66 src/cljs/argo/vec.cljs
WARNING: Use of undeclared Var cljs.core/seq at line 66 src/cljs/argo/vec.cljs
WARNING: Use of undeclared Var cljs.core/chunked-seq? at line 66 src/cljs/argo/vec.cljs
WARNING: Use of undeclared Var cljs.core/chunk-first at line 1649 src/cljs/argo/vec.cljs
WARNING: Use of undeclared Var cljs.core/count at line 66 src/cljs/argo/vec.cljs
WARNING: Use of undeclared Var cljs.core/chunk-buffer at line 66 src/cljs/argo/vec.cljs
WARNING: Use of undeclared Var cljs.core/-nth at line 66 src/cljs/argo/vec.cljs
WARNING: Use of undeclared Var cljs.core/chunk-append at line 66 src/cljs/argo/vec.cljs
WARNING: Use of undeclared Var cljs.core/chunk-cons at line 66 src/cljs/argo/vec.cljs
WARNING: Use of undeclared Var cljs.core/chunk at line 66 src/cljs/argo/vec.cljs
WARNING: Use of undeclared Var cljs.core/chunk-rest at line 66 src/cljs/argo/vec.cljs
WARNING: Use of undeclared Var cljs.core/chunk-cons at line 66 src/cljs/argo/vec.cljs
WARNING: Use of undeclared Var cljs.core/chunk at line 66 src/cljs/argo/vec.cljs
WARNING: Use of undeclared Var cljs.core/first at line 66 src/cljs/argo/vec.cljs
WARNING: Use of undeclared Var cljs.core/cons at line 66 src/cljs/argo/vec.cljs
WARNING: Use of undeclared Var cljs.core/rest at line 66 src/cljs/argo/vec.cljs
WARNING: Use of undeclared Var cljs.core/LazySeq at line 67 src/cljs/argo/vec.cljs
...hundreds of lines...
```

Then the final generated documents are completely empty.

```
$ ls doc
css  index.html  js
```

The head of vec.cljs looks like
```
(ns
    ^{:doc "Vectors with 2 Dimensions"}
    argo.vec
    (:require
     [goog.vec.Vec2 :as Vec2]))

(def ^{:dynamic true
       :doc "The fuzzy zone size for the almost comparitor"}
  *almost-delta* 1e-14)

(def
  ^{:arglist '([x y])
    :doc "Create a two dimensional vector #<x,y>"}
  vec2 Vec2/createFloat64FromValues)

... the rest is normal cljs
```

Is there an example cljs project that I can compare with?

**Comment by weavejester** [comment]
The `codox.example` directory in the repository contains an example project for Codox. It includes several ClojureScript namespaces, and a `:cljs` profile for generating documentation for ClojureScript.

For documentation purposes, the version of ClojureScript being used matters, as older versions of the reader skip over var metadata used for documentation.

**Comment by retrogradeorbit** [comment]
I extract the codox master branch, go into example (codox-0.8.12), and `lein with-profile cljs doc` and the documents are correctly generated. I notice it also prints these warnings, so I think the warnings I'm getting are a red herring.

I compared the project.clj's and the example project file is missing the :dependency of clojurescript completely. I take out the clojurescript dependency and the docs build successfully!

Im using a pretty recent clojurescript, 0.0-3211.

Moving backwards through the versions, did a bit of a binary search to see where things got broken.

So clojurescript up to version 0.0-2985 works. (I tested from 2843)

Then it breaks in 0.0.3030 and up until the latest 0.0.3211.

**Comment by retrogradeorbit** [comment]
Just thought I'd leave my **workaround** here on the ticket:

add a profile that downgrades the clojurescript version, like

```
:profiles {:doc {:dependencies [[org.clojure/clojurescript "0.0-2985"]]}}
```

and then build docs with

```
lein with-profile doc doc
```

**Comment by bilus** [comment]
Thanks @retrogradeorbit, this has been very helpful. You can also define an alias to make sure you never forget to use `with-profile`:

```clojure
:aliases {"doc" ["with-profile" "doc" "doc"]}
```
