### ISSUE TITLE
Any idea why my namespaces are showing up twice?

### ISSUE THREAD

**Issue by brunchboy** [weavejester/codox#93]
I just discovered codox, and am very excited about its potential to add detailed API documentation to my project. But for some reason, my namespaces are all showing up twice on the index page, is that something I am doing wrong?

http://deepsymmetry.org/afterglow/doc

The project is here, if you want to glance at the project.clj:
https://github.com/brunchboy/afterglow

Thanks for any help you can give me!

**Comment by weavejester** [comment]
I think it might be because you add the `src` path twice. Once in your base project, and once in your dev profile. Because `:source-paths` is a vector, rather than a set, it doesn't inherently weed out duplicate paths, and Codox doesn't either (patches welcome!).

**Comment by brunchboy** [comment]
Ah ha! Thanks, that does seem to be it, and it looks like this is an error in my project configuration, more than in codox. I seem to be able to get the protocol buffers compiled to Java and my REPL launched just fine without the redundant copies of those files in my dev profile. I will just get rid of that, rather than submitting a PR to codox. (And not just because I have spent most of the day submitting pull requests to other projects rather than working on my own code! ;^)
