### ISSUE TITLE
Docs not being generated for cljc files

### ISSUE THREAD

**Issue by danielcompton** [weavejester/codox#97]
Although I see that Codox has been updated to support cljc files, it doesn't seem to be picking them up. Running Codox against https://github.com/apa512/clj-rethinkdb/commit/69c092753559985006aff922807b2daad33a94bb it only generates pages for .clj files, not cljc. Running against https://github.com/apa512/clj-rethinkdb/commit/e9dc902b3deafc974d6475496f04e8ef0d4ad9b6 (before converting to .cljc), all pages were generated.

**Comment by danielcompton** [comment]
One thing that may not make this immediately obvious is that pages aren't deleted by `lein doc`. So the HTML files will stay around until you do a clean build.

**Comment by weavejester** [comment]
I'm afraid I can't reproduce your issue. On that commit, with a clean project directory, everything appears to work fine. I even tried wiping Codox from my .m2 cache just to see if I had any problems there.

**Comment by weavejester** [comment]
Could you try a `lein clean` or `git clean -fxd` and see if that works?

**Comment by danielcompton** [comment]
A lein clean and rerun fixed it. Sorry for the trouble, and thanks for your help.
